DROP TABLE Archive_Student;

CREATE TABLE Archive_Student
AS (SELECT * FROM Student);

CREATE OR REPLACE TRIGGER onDelete
AFTER DELETE ON Student

BEGIN
INSERT INTO Archive_Student
(STDID,FNAME,LNAME,MI,MAJORID,ADDRESS,CITY,STATE,ZIP,PHONE,ADVID)
SELECT * FROM Student; 
END;
